# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name pvalue
#' @title A function to calculate the p-value for the Sharpe ratio
#' @description This function calculates the p-value for the Sharpe ratio
#' @param r Numeric vector of returns
#' @param r0 Numeric vector of benchmark returns
#' @return p-value for the Sharpe ratio
#' @examples
#' \dontrun{
#' r <- rnorm(100)
#' r0 <- rnorm(100)
#' pvalue(r, r0)
#' }
#' @export
pvalue <- function(r, r0) {
    .Call('_SA24204169_pvalue', PACKAGE = 'SA24204169', r, r0)
}

